### ISSUE TITLE
Abnormally large number of hits in first event using qpixg4/v3.0.0

### ISSUE THREAD

**Issue by Eikenbcr** [Q-Pix/Q_PIX_GEANT4#26]
Users have reported that when using qpixg4/v3.0.0, there was an abnormally large number of hits (~O(18)) in the first event. I haven't seen this in my samples, however, I made them with qpixg4/v2.0.0. There is a possibility that the number_hits_  variable in AnalysisData::EventReset() is not being properly initialized. 

Previously in qpixg4/v2.0.0, we had number_hits_ variable initialized in AnalysisManager::EventReset() as an 'int' type object and cleared with number_hits_ = 0;

In qpixg4/v3.0.0 we have number_hits_ variable initialized in AnalysisData::EventReset() as a 'Long64_t' type object which is a ROOT defined type that we are clearing with number_hits_ = 0;

**Comment by Eikenbcr** [comment]
If 'Long64_t' is a locally defined variable then it may be getting initialized with a random non-zero value. @kelseymh Should we define number_hits_ as a 'long' or 'long long'?

**Comment by kelseymh** [comment]
`Long64_t` is a _type_.  In your .h or .cpp file, you can always add `#include "Rtypes.h"` to get the ROOT type declarations.  Then you can define data members or local variables with the correct ROOT type and initialize it properly.  The variable's local type should always _match_ whatever "type suffix" (like /C, /I, /D, etc.) you use later in your TBranch instantiation.  Otherwise, what happens is that TBranch will map the number of bytes of memory specified by the suffix, which may not match the number of bytes allocated to the variable.

**Comment by Eikenbcr** [comment]
From 'Rtypes.h',

```
  110 const ULong64_t kMaxULong64  = ULong64_t(~0LL);
  111 const Long64_t  kMaxLong64   = Long64_t(kMaxULong64 >> 1);
  112 const Long64_t  kMinLong64   = -kMaxLong64 - 1;
```
and in 'RtypesCore.h'

`typedef long long          Long64_t; //Portable signed long integer 8 bytes`

From our code,

    event_tree_->Branch("number_hits",      &event.number_hits_,      "number_hits/L");

Should we change to number_hits/LL?

**Comment by kelseymh** [comment]
> Should we change to number_hits/LL?

See TTree::Branch() [11/13] (https://root.cern/doc/v632/classTTree.html#ac1fa9466ce018d4aa739b357f981c615).  You use "/L" for Long64_t.  So you should declare the variable that you're putting into the `Branch()` function using type `Long64_t`, initialize it to zero, and then use it in the `Branch()` call with a "/L" suffix.

**Comment by Eikenbcr** [comment]
Running the same ReleaseBuilder version (qpixg4/v3.0.0 and qpixrtd/v2.0.0) and Warmup macro as others, I was still unable to reproduce this problem.

**Comment by Eikenbcr** [comment]
We are initializing number_hits_ in AnalysisData.h as 
`Long64_t number_hits_; ` 
could we test whether 
`Long64_t number_hits_{0}; ` or `Long64_t number_hits_ = 0; `
fixes the issue?

**Comment by kelseymh** [comment]
So std::vector's don't need to be initialized, but all of the non-vector data members should be initialized.  The proper way to initialize data members is in the constructor ([AnalysisData.cpp](https://github.com/Q-Pix/qpixg4/blob/53cb99d5ef7564c47e95fa618ecc582e1ca95d0a/src/AnalysisData.cpp#L19)) using the normal syntax,
```
   AnalysisData::AnalysisData() : run_(0), event_(0), number_particles_(0),
```
and so on, listing each of the data members in the order they appear in the .h file.

**Comment by kelseymh** [comment]
I see, as you noted, that number_hits_ is properly declared as a Long64_t, and it is also reset to zero in the `EventReset()` function.  Since `EventReset()` is not virtual, you might consider calling it in the constructor to perform the initialization, rather than using the initializer list above.

**Comment by Eikenbcr** [comment]
So are you suggesting that we change ([AnalysisData.cpp](https://github.com/Q-Pix/qpixg4/blob/53cb99d5ef7564c47e95fa618ecc582e1ca95d0a/src/AnalysisData.cpp#L19)) with the following:

AnalysisData::AnalysisData()
{
#ifdef G4ANALYSIS_USE
#endif
EventReset()
}

**Comment by ashmanskas** [comment]
Yes, this change indeed makes the reported problem disappear.  Without this change, anyone who wants to use 3.0.0 needs to apply this change as an ad-hoc patch before compiling.

> So are you suggesting that we change ([AnalysisData.cpp](https://github.com/Q-Pix/qpixg4/blob/53cb99d5ef7564c47e95fa618ecc582e1ca95d0a/src/AnalysisData.cpp#L19)) with the following:
> 
> AnalysisData::AnalysisData() { #ifdef G4ANALYSIS_USE #endif EventReset() }

**Comment by Eikenbcr** [comment]
The fix suggested here was added to qpixg4/develop branch. #27

**Comment by Eikenbcr** [comment]
I was able to generate a small sample of muon events successfully with the changes on develop. Can other groups test the develop branch with Geant4/10.7.x to see if these changes work as expected?
